In [1]:
from script import *

[nltk_data] Downloading package stopwords to C:\Users\JATIN PRATAP
[nltk_data]     SINGH\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [2]:
#importing the synthetic dataset
df1 = pd.read_csv("Datasets/synthetic_hate_speech_dataset.csv")

In [3]:
#importing the real dataset and then creating a random sample out of it
# df2 = pd.read_csv("Datasets/HateSpeechDataset.csv")
# sampling(df = df2, n=4000)

#this cell was to be run only once just to create the random sample, for future this is being commented out
#but still here just for others to get the reference.

In [4]:
# non_hate = df2[df2["Label"] == 0].sample(n = 1000, random_state=0)

In [5]:
# non_hate.head()

In [6]:
# non_hate.to_csv('Datasets/random_sample.csv', mode='a', header=False, index=False)

In [7]:
df2 = pd.read_csv("Datasets/random_sample.csv")

In [8]:
df1["Content"] = df1["Content"].astype(df2["Content"].dtype)

In [9]:
df = pd.concat([df1, df2], axis = 0, ignore_index=True)

In [10]:
df["Label"].value_counts()

Label
0    6494
1    5506
Name: count, dtype: int64

In [11]:
df.tail()

Content  Label
11995  she can just fucking call the venue about it a...      0
11996  solanus casey please do not copy and paste mat...      0
11997  so aussie you reckon it should be put as colli...      0
11998  dear apology accepted regarding the link and i...      0
11999  i think that the brushstrokes series article s...      0

In [12]:
df.head()

Content  Label
0  religion is suffering because of citizens of c...      1
1  Understanding and respect are key in politics ...      0
2  Everyone should have equal rights in politics,...      0
3  Diversity in politics makes it more vibrant an...      0
4   disability is suffering because of team members.      1

In [13]:
#preprocessing using the script 
corpus = preprocessing(df["Content"])

In [14]:
corpus

array([[ 160,    9,  152, ...,    0,    0,    0],
       [ 140,    8,  131, ...,    0,    0,    0],
       [ 106,   32,   18, ...,    0,    0,    0],
       ...,
       [  33, 3910,    6, ...,    0,    0,    0],
       [1151, 2505, 1156, ...,  836,    7,  390],
       [   5,   70,   13, ...,    0,    0,    0]], dtype=int32)

In [15]:
corpus.shape

(12000, 100)

In [16]:
x = corpus

In [17]:
y = df["Label"].values

In [18]:
#splitting the dataset for training and testing
x_train, x_test, y_train, y_test = split(x, y)

In [19]:
#initializing the sequential model with LSTM layer on the training set after performing the embedding
model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=128, input_length=max_len),
    LSTM(64),
    Dense(1, activation='sigmoid')  # Binary classification
])

c:\Users\JATIN PRATAP SINGH\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [20]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [21]:
model.fit(x_train, y_train, epochs=10, batch_size=32, validation_data=(x_test, y_test))

Epoch 1/10
300/300 ━━━━━━━━━━━━━━━━━━━━ 10s 29ms/step - accuracy: 0.5471 - loss: 0.6885 - val_accuracy: 0.5350 - val_loss: 0.6817
Epoch 2/10
300/300 ━━━━━━━━━━━━━━━━━━━━ 9s 29ms/step - accuracy: 0.5338 - loss: 0.6718 - val_accuracy: 0.5367 - val_loss: 0.6742
Epoch 3/10
300/300 ━━━━━━━━━━━━━━━━━━━━ 10s 34ms/step - accuracy: 0.5631 - loss: 0.6466 - val_accuracy: 0.7504 - val_loss: 0.5171
Epoch 4/10
300/300 ━━━━━━━━━━━━━━━━━━━━ 10s 33ms/step - accuracy: 0.8226 - loss: 0.4275 - val_accuracy: 0.8517 - val_loss: 0.3426
Epoch 5/10
300/300 ━━━━━━━━━━━━━━━━━━━━ 10s 33ms/step - accuracy: 0.9339 - loss: 0.1893 - val_accuracy: 0.8550 - val_loss: 0.3592
Epoch 6/10
300/300 ━━━━━━━━━━━━━━━━━━━━ 10s 33ms/step - accuracy: 0.9718 - loss: 0.0905 - val_accuracy: 0.8446 - val_loss: 0.4297
Epoch 7/10
300/300 ━━━━━━━━━━━━━━━━━━━━ 11s 35ms/step - accuracy: 0.9840 - loss: 0.0516 - val_accuracy: 0.8517 - val_loss: 0.5050
Epoch 8/10
300/300 ━━━━━━━━━━━━━━━━━━━━ 11s 35ms/step - accuracy: 0.9930 - loss: 0.0261 - v

In [22]:
#predicting the test set results
y_pred = model.predict(x_test)

75/75 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step


In [23]:
y_pred = (y_pred > 0.5).astype(int)

In [24]:
#evaluating the model's performance
evaluation(y_test=y_test, y_pred=y_pred)

'The accuracy score for the actual and predicted values is 0.83875 \nand the confusion matrix is [[1030  253]\n [ 134  983]]'

In [32]:
single_inp = clean_input("Everyone deserves to be treated with kindness and respect, no matter their background.")

In [33]:
single_inp.shape

(1, 100)

In [34]:
model.predict(single_inp)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step


array([[0.0007238]], dtype=float32)

In [35]:
single_inp_2 = clean_input("People of this group are retarded, they dont belong here")

In [36]:
single_inp_2.shape

(1, 100)

In [37]:
model.predict(single_inp_2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step


array([[0.9990677]], dtype=float32)

In [38]:
#dumping the trained model and tokenizer
import joblib
joblib.dump(model, 'Model/model.joblib')
joblib.dump(tokenizer, 'Model/tokenizer.joblib')

['Model/tokenizer.joblib']