In [29]:
from script import *

In [30]:
#importing the dataset with only first 2000 rows
df1 = pd.read_csv("Datasets/synthetic_hate_speech_dataset.csv")
df2 = pd.read_csv("Datasets/HateSpeechDataset.csv")

In [31]:
df2["Content"] = df2["Content"].astype(df1["Content"].dtype)

In [32]:
df = pd.concat([df1, df2.iloc[:3000,:]], axis = 0, ignore_index=True)

In [33]:
df.tail()

Content  Label
5995  behind every avatar is an actual person and wh...      0
5996                                i ve seen it happen      0
5997          brother you remind me of a young meatloaf      0
5998                       awesome band back in the day      0
5999                             hell of a show as well      0

In [34]:
df.head()

Content  Label
0  religion is suffering because of citizens of c...      1
1  Understanding and respect are key in politics ...      0
2  Everyone should have equal rights in politics,...      0
3  Diversity in politics makes it more vibrant an...      0
4   disability is suffering because of team members.      1

In [35]:
#preprocessing using the script 
corpus = preprocessing(df["Content"])

In [36]:
corpus

['religion suffer citizen countri',
 'understand respect key polit regardless one team member',
 'everyon equal right polit includ team member',
 'divers polit make vibrant inclus',
 'disabl suffer team member',
 'citizen countri allow nation space',
 'profess suffer student school z',
 'group b allow nation space',
 'stand peopl region x sexual orient worst',
 'employe allow sexual orient space',
 'divers gender make vibrant inclus',
 'divers sport make vibrant inclus',
 'everi problem polit caus team member',
 'everi problem sport caus group',
 'peopl group b ruin educ',
 'peopl commun c ruin profess',
 'student school z contribut posit profess mani way',
 'everyon equal right sexual orient includ citizen countri',
 'need support peopl region x religion better societi',
 'understand respect key sexual orient regardless one group',
 'citizen countri allow educ space',
 'commun c contribut posit religion mani way',
 'everyon equal right sexual orient includ group',
 'divers nation make

In [37]:
x, y = vectorizer(corpus = corpus, df = df["Label"])

In [38]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [39]:
y

array([1, 0, 0, ..., 0, 0, 0])

In [40]:
#splitting the dataset for training and testing
x_train, x_test, y_train, y_test = split(x, y)

In [41]:
#training the random_forest model on the training set
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(x_train, y_train)

RandomForestClassifier()

In [42]:
#predicting the test set results
y_pred = model.predict(x_test)

In [43]:
#evaluating the model's performance
evaluation(y_test=y_test, y_pred=y_pred)

'The accuracy score for the actual and predicted values is 0.92 \nand the confusion matrix is [[724   7]\n [ 89 380]]'

In [44]:
single_inp = clean_input("I think we should work towards mutual understanding")

In [45]:
single_inp.shape

(1, 4888)

In [46]:
model.predict(single_inp)

array([0])

In [47]:
model.predict_proba(single_inp)

array([[0.92, 0.08]])

In [48]:
single_inp_2 = clean_input("People of this group are retarded, they dont belong here")

In [49]:
single_inp_2.shape

(1, 4888)

In [50]:
model.predict(single_inp_2)

array([1])

In [51]:
model.predict_proba(single_inp_2)

array([[0.15, 0.85]])